### PR TITLE
Changed author in pack.yaml to align with other packs.

### PR DESCRIPTION
**Pull request by jensihnow**

### CODE REVIEW

**Comment by LindsayHill** [comment]
`StackStorm` is the correct name, not `Stackstorm`. Which other packs have `Stackstorm`?

From a quick look through my local copy of the Exchange packs, `StackStorm, Inc.` is much more common, and I don't have any with `Stackstorm, Inc`:

```sh
[/c/Users/lhill/github/exchange]
[lhill][775RP72] $ grep author */pack.yaml|grep -c 'Stackstorm, Inc'
0

[/c/Users/lhill/github/exchange]
[lhill][775RP72] $ grep author */pack.yaml|grep -c 'StackStorm, Inc'
40

[/c/Users/lhill/github/exchange]
[lhill][775RP72] $
```

**Comment by jensihnow** [comment]
Maybe I got outdated versions of the pack, since I ran into:

image

**Comment by LindsayHill** [comment]
@jensihnow no, actually it's something else going on. Those other packs are part of the core code (github.com/StackStorm/st2), not distributed via exchange.stackstorm.org. That's why I didn't see them with my `grep` earlier. It's also why they're different, and those other ones should be fixed, not this one.

**Comment by LindsayHill** [comment]
I'll do a PR to fix those other ones.

**Pull request closed without merging**
