### PR TITLE
Fixed action auto-generator and update action latest API spec

### PR DESCRIPTION
**Pull request by nmaludy**
Went to fix an action in this pack and notice that the action auto-generator was busted. Both of them.

Fixed the action auto-generator to now work with both the OpenAPI spec and HTTP reference documentation. The goal here is to transition 100% to the OpenAPI spec as that spec gets bugs fixed in it.

The bugs that are there currently are:
 - Defaults for the parameters are missing from the spec
 - Some of the API endpoints have different HTTP methods compared to the HTTP reference documentation (this might not be a bug?)

This is fairly large change so i'm bumping the major version for the pack.

### CODE REVIEW

**Comment by nmaludy** [comment]
@shusugmt if you get some time could you please review this?

I know you've had some other PRs previously related to this, but i tried to summarize everything into one up-to-date PR.

**Comment by nmaludy** [comment]
For anyone reviewing, here is a link to the auto-generator code: https://github.com/StackStorm-Exchange/stackstorm-slack/pull/55/files#diff-aa9b75ed7de54912a8f30b63f77e8bcd

**Comment by shusugmt** [comment]
@nmaludy At the time I did this, the OpenAPI spec was missing some descriptions: see #47 and #49, and the new generator introduced in this PR seems to use spec from web page only for complementing default value for params, do nothing around description. Is that problem fixed on Slack OpenAPI spec side? Or in other words: can we now trust that repo?

OT: I thought it's easier for reviewers if the PR for `actions/*` is opened separately... this was massive.

**Comment by nmaludy** [comment]
@shusugmt Yes, looks like the descriptions are fixed now. Let me break the "action generator" changes off into another PR, then when those get merged in this PR will just contain the `action/*` changes.

Does that work?

**Comment by shusugmt** [comment]
Nah, that's fine, I already saw the actual code change. This time the important change was made in `bin/*` and that comes after all auto-generated `actions/*` which makes me keep scrolling down to the bottom.

LGTM!

#47 #48 #49 should be closed after this gets merged.

**Pull request merged**
